services:
  byd-website:
    build: ./website-with-chatbot
    container_name: byd-website
    ports:
      - "8082:3000"
    restart: unless-stopped
    networks:
      - byd-network

networks:
  byd-network:
    driver: bridge
