const state={models:[],settings:{hero:{}}};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value||'').replace(/[&<>']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[char]));
const getYouTubeId=url=>String(url||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{11})/)?.[1]||'';
const sidebar=$('#adminSidebar');
if(localStorage.getItem('byd-admin-sidebar')==='collapsed')sidebar.classList.add('collapsed');
$('#collapseSidebar').addEventListener('click',()=>{sidebar.classList.toggle('collapsed');localStorage.setItem('byd-admin-sidebar',sidebar.classList.contains('collapsed')?'collapsed':'expanded');$('#collapseSidebar').setAttribute('aria-label',sidebar.classList.contains('collapsed')?'Expand sidebar':'Minimize sidebar')});
const pageInfo={overview:['Website Overview','Manage the content customers see on your website.'],hero:['Homepage Hero','Update the first visual and message customers see.'],vehicles:['Vehicle Catalogue','Manage model information, images and visibility.']};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');setTimeout(()=>el.className='toast',2800)}
function showPage(name){document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));$(`#${name}Page`).classList.add('active');document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.page===name));$('#pageTitle').textContent=pageInfo[name][0];$('#pageSubtitle').textContent=pageInfo[name][1];$('#topAction').textContent=name==='vehicles'?'+ Add vehicle':name==='hero'?'View website':'Manage homepage';$('#topAction').dataset.page=name==='overview'?'hero':name;window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item,.go-page').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));
$('#topAction').addEventListener('click',()=>{$('#topAction').dataset.page==='vehicles'?openVehicle():$('#topAction').dataset.page==='hero'?window.open('/','_blank'):showPage($('#topAction').dataset.page)});

async function loadAll(){const [modelsResponse,settingsResponse]=await Promise.all([fetch('/api/content/models'),fetch('/api/content/settings')]);state.models=await modelsResponse.json();state.settings=await settingsResponse.json();renderMetrics();renderHeroForm();renderVehicles()}
function renderMetrics(){const published=state.models.filter(model=>model.published!==false).length;$('#vehicleMetric').textContent=published;$('#heroMetric').textContent=state.settings.hero?.mediaType==='video'?'Video':'Image'}
function renderHeroForm(){const hero=state.settings.hero||{};const form=$('#heroForm');['eyebrow','headline','description','mediaUrl'].forEach(name=>form.elements[name].value=hero[name]||'');form.elements.mediaType.value=hero.mediaType||'image';updateMediaGuidance();updateHeroPreview(hero.mediaUrl,hero.mediaType)}
function updateMediaGuidance(){const type=$('#heroForm').elements.mediaType.value,isVideo=type==='video',file=$('#heroFile');$('#mediaGuidance').textContent=isVideo?'Video mode is active. Paste a YouTube link or upload an MP4/WEBM file; it will autoplay silently and loop.':'Image mode is active. Upload a JPG, PNG or WEBP image.';$('#heroDropTitle').textContent=isVideo?'Choose a new video':'Choose a new image';$('#heroDropHelp').textContent=isVideo?'MP4 or WEBM · maximum 60 MB':'JPG, PNG or WEBP · maximum 60 MB';file.accept=isVideo?'video/mp4,video/webm':'image/jpeg,image/png,image/webp';file.value=''}
function updateHeroPreview(url,type){const preview=$('#heroPreview');preview.querySelectorAll('video,iframe').forEach(media=>media.remove());preview.style.backgroundImage='';if(!url)return;if(type==='video'){const youtubeId=getYouTubeId(url);if(youtubeId){const iframe=document.createElement('iframe');iframe.src=`https://www.youtube.com/embed/${youtubeId}?autoplay=1&mute=1&loop=1&playlist=${youtubeId}&controls=0&rel=0&playsinline=1&cc_load_policy=0`;iframe.allow='autoplay; encrypted-media';iframe.title='Hero video preview';preview.prepend(iframe)}else{const video=document.createElement('video');video.src=url;video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;preview.prepend(video)}}else preview.style.backgroundImage=`url("${String(url).replace(/["\\]/g,'')}")`}
function syncPreviewText(){const form=$('#heroForm');$('#previewEyebrow').textContent=form.eyebrow.value||'Build Your Dreams';$('#previewHeadline').textContent=form.headline.value||'Electrify Your Journey';$('#previewDescription').textContent=form.description.value||'Discover the full range of BYD vehicles.'}
$('#heroForm').addEventListener('input',syncPreviewText);
document.querySelectorAll('input[name="mediaType"]').forEach(input=>input.addEventListener('change',updateMediaGuidance));
$('#heroFile').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const type=file.type.startsWith('video/')?'video':'image';$('#heroForm').elements.mediaType.value=type;updateHeroPreview(URL.createObjectURL(file),type)});
$('#heroForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,message=$('#heroMessage'),button=form.querySelector('button[type="submit"]');button.disabled=true;message.className='form-message';message.textContent='Saving...';try{const response=await fetch('/api/content/settings/hero',{method:'PUT',body:new FormData(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save');state.settings.hero=result;renderMetrics();updateHeroPreview(result.mediaUrl,result.mediaType);message.className='form-message success';message.textContent='Homepage updated successfully.';toast('Homepage hero updated')}catch(error){message.className='form-message error';message.textContent=error.message;toast(error.message,true)}finally{button.disabled=false}});

function renderVehicles(filter=''){const list=$('#vehicleList'),query=filter.toLowerCase();const models=state.models.filter(model=>`${model.name} ${model.type}`.toLowerCase().includes(query));$('#vehicleCount').textContent=`${models.length} vehicle${models.length===1?'':'s'}`;list.innerHTML=models.length?models.map(model=>`<article class="vehicle-card"><img src="${esc(model.image)}" alt="${esc(model.name)}"><div class="vehicle-card-body"><div class="vehicle-card-top"><div><h3>${esc(model.name)}</h3><p>${esc(model.type)} · ${esc(model.price)}</p></div><span class="status ${model.published?'':'hidden'}">${model.published?'Published':'Hidden'}</span></div><p>${esc(model.description)}</p><div class="vehicle-card-actions"><button class="secondary" onclick="editVehicle('${esc(model.id)}')">Edit details</button><button class="secondary danger" onclick="deleteVehicle('${esc(model.id)}')">Delete</button></div></div></article>`).join(''):'<p>No matching vehicles found.</p>'}
$('#vehicleSearch').addEventListener('input',event=>renderVehicles(event.target.value));
function renderGalleryPreview(images=[]){$('#vehicleGalleryPreview').innerHTML=images.filter(Boolean).map(image=>`<img src="${esc(image)}" alt="Vehicle gallery preview">`).join('')}
function openVehicle(model){const form=$('#vehicleForm');form.reset();form.editingId.value='';form.published.checked=true;renderGalleryPreview();$('#vehicleFormTitle').textContent='Add new vehicle';$('#vehicleMessage').textContent='';if(model){Object.entries(model).forEach(([key,value])=>{if(form.elements[key]&&key!=='published'&&key!=='images')form.elements[key].value=value||''});form.editingId.value=model.id;form.published.checked=!!model.published;$('#vehicleFormTitle').textContent=`Edit ${model.name}`;renderGalleryPreview(Array.isArray(model.images)&&model.images.length?model.images:[model.image])}$('#vehicleModal').classList.add('open');document.body.style.overflow='hidden'}
function closeVehicle(){$('#vehicleModal').classList.remove('open');document.body.style.overflow=''}
window.editVehicle=id=>openVehicle(state.models.find(model=>model.id===id));
window.deleteVehicle=async id=>{const model=state.models.find(item=>item.id===id);if(!confirm(`Delete ${model?.name||'this vehicle'}? You can hide it instead by editing the listing.`))return;const response=await fetch('/api/content/models/'+id,{method:'DELETE'});if(!response.ok)return toast('Unable to delete vehicle',true);toast('Vehicle deleted');await refreshModels()};
$('#addVehicle').onclick=()=>openVehicle();$('#closeVehicle').onclick=closeVehicle;$('#cancelVehicle').onclick=closeVehicle;$('#vehicleModal').addEventListener('click',event=>{if(event.target.id==='vehicleModal')closeVehicle()});
$('#vehicleFile').addEventListener('change',event=>{const files=[...event.target.files].slice(0,8);renderGalleryPreview(files.map(file=>URL.createObjectURL(file)))});
async function refreshModels(){const response=await fetch('/api/content/models');state.models=await response.json();renderMetrics();renderVehicles($('#vehicleSearch').value)}
$('#vehicleForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),id=data.get('editingId'),message=$('#vehicleMessage'),button=form.querySelector('button[type="submit"]');data.delete('editingId');data.set('published',form.published.checked?'true':'false');button.disabled=true;message.textContent='Saving...';try{const response=await fetch(id?'/api/content/models/'+id:'/api/content/models',{method:id?'PUT':'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save');await refreshModels();closeVehicle();toast(id?'Vehicle updated':'Vehicle added')}catch(error){message.className='form-message error';message.textContent=error.message}finally{button.disabled=false}});
loadAll().catch(error=>toast('Unable to load website content',true));
