const state={models:[],settings:{heroSlides:[]}};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value||'').replace(/[&<>']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[char]));
const getYouTubeId=url=>String(url||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{11})/)?.[1]||'';
const sidebar=$('#adminSidebar');
if(localStorage.getItem('byd-admin-sidebar')==='collapsed')sidebar.classList.add('collapsed');
$('#collapseSidebar').addEventListener('click',()=>{sidebar.classList.toggle('collapsed');localStorage.setItem('byd-admin-sidebar',sidebar.classList.contains('collapsed')?'collapsed':'expanded');$('#collapseSidebar').setAttribute('aria-label',sidebar.classList.contains('collapsed')?'Expand sidebar':'Minimize sidebar')});
const pageInfo={overview:['Website Overview','Manage the content customers see on your website.'],hero:['Homepage Slides','Manage homepage images, videos, buttons and display order.'],vehicles:['Vehicle Catalogue','Manage model information, images and visibility.']};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');setTimeout(()=>el.className='toast',2800)}
function showPage(name){document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));$(`#${name}Page`).classList.add('active');document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.page===name));$('#pageTitle').textContent=pageInfo[name][0];$('#pageSubtitle').textContent=pageInfo[name][1];$('#topAction').textContent=name==='vehicles'?'+ Add vehicle':name==='hero'?'View website':'Manage homepage';$('#topAction').dataset.page=name==='overview'?'hero':name;window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item,.go-page').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));
$('#topAction').addEventListener('click',()=>{$('#topAction').dataset.page==='vehicles'?openVehicle():$('#topAction').dataset.page==='hero'?window.open('/','_blank'):showPage($('#topAction').dataset.page)});

async function loadAll(){const [modelsResponse,settingsResponse]=await Promise.all([fetch('/api/content/models'),fetch('/api/content/settings')]);state.models=await modelsResponse.json();state.settings=await settingsResponse.json();state.settings.heroSlides=Array.isArray(state.settings.heroSlides)?state.settings.heroSlides:state.settings.hero?[{...state.settings.hero,id:'legacy-hero',priority:1,published:true,duration:7000,buttons:[]}]:[];renderMetrics();renderHeroSlides();resetHeroForm();renderVehicles()}
function sortedSlides(){return [...state.settings.heroSlides].sort((a,b)=>(Number(a.priority)||999)-(Number(b.priority)||999))}
function renderMetrics(){const published=state.models.filter(model=>model.published!==false).length,slides=state.settings.heroSlides.filter(slide=>slide.published!==false);$('#vehicleMetric').textContent=published;$('#heroMetric').textContent=`${slides.length} slide${slides.length===1?'':'s'}`}
function renderHeroSlides(){const slides=sortedSlides();$('#heroSlideList').innerHTML=slides.length?slides.map(slide=>`<article class="slide-list-card ${slide.published===false?'unpublished':''}"><div class="slide-thumb" style="background-image:url('${slide.mediaType==='image'?esc(slide.mediaUrl):''}')"><span>${slide.mediaType==='video'?'VIDEO':'IMAGE'}</span></div><div class="slide-card-copy"><small>Priority ${esc(slide.priority)} · ${Math.round((slide.duration||7000)/1000)} sec</small><strong>${esc(slide.headline)}</strong><span>${slide.published===false?'Hidden':'Published'} · ${slide.buttons?.length||0} button${slide.buttons?.length===1?'':'s'}</span></div><div class="slide-card-actions"><button class="secondary compact" type="button" onclick="editHeroSlide('${esc(slide.id)}')">Edit</button><button class="secondary compact danger" type="button" onclick="deleteHeroSlide('${esc(slide.id)}')">Delete</button></div></article>`).join(''):'<div class="empty-state">No homepage slides yet. Add the first slide.</div>'}
function addButtonRow(button={}){const row=document.createElement('div');row.className='button-row';row.innerHTML=`<input class="button-label" placeholder="Button label" value="${esc(button.label||'')}"><input class="button-link" list="linkTargets" placeholder="#news or https://..." value="${esc(button.href||'')}"><select class="button-style"><option value="primary" ${button.style!=='outline'?'selected':''}>Primary</option><option value="outline" ${button.style==='outline'?'selected':''}>Outline</option></select><button type="button" class="remove-button" aria-label="Remove button">×</button>`;row.querySelector('.remove-button').onclick=()=>{row.remove();syncPreviewText()};row.addEventListener('input',syncPreviewText);$('#slideButtons').appendChild(row)}
function resetHeroForm(){const form=$('#heroForm');form.reset();form.editingId.value='';form.priority.value=state.settings.heroSlides.length?Math.max(...state.settings.heroSlides.map(item=>Number(item.priority)||0))+1:1;form.durationSeconds.value=7;form.published.checked=true;$('#heroFormTitle').textContent='Add homepage slide';$('#heroEditStatus').textContent='New';$('#heroMessage').textContent='';$('#slideButtons').innerHTML='';addButtonRow({label:'View Events',href:'#news',style:'primary'});updateMediaGuidance();updateHeroPreview('','image');syncPreviewText()}
function renderHeroForm(slide){const form=$('#heroForm');form.reset();form.editingId.value=slide.id;['eyebrow','headline','description','mediaUrl','priority'].forEach(name=>form.elements[name].value=slide[name]??'');form.durationSeconds.value=Math.round((slide.duration||7000)/1000);form.elements.mediaType.value=slide.mediaType||'image';form.published.checked=slide.published!==false;$('#heroFormTitle').textContent=`Edit ${slide.headline}`;$('#heroEditStatus').textContent=`Priority ${slide.priority}`;$('#heroMessage').textContent='';$('#slideButtons').innerHTML='';(slide.buttons||[]).forEach(addButtonRow);updateMediaGuidance();updateHeroPreview(slide.mediaUrl,slide.mediaType);syncPreviewText()}
function updateMediaGuidance(){const type=$('#heroForm').elements.mediaType.value,isVideo=type==='video',file=$('#heroFile');$('#mediaGuidance').textContent=isVideo?'Video mode is active. Paste a YouTube link or upload an MP4/WEBM file; it will autoplay silently and loop.':'Image mode is active. Upload a JPG, PNG or WEBP image.';$('#heroDropTitle').textContent=isVideo?'Choose a new video':'Choose a new image';$('#heroDropHelp').textContent=isVideo?'MP4 or WEBM · maximum 60 MB':'JPG, PNG or WEBP · maximum 60 MB';file.accept=isVideo?'video/mp4,video/webm':'image/jpeg,image/png,image/webp';file.value=''}
function updateHeroPreview(url,type){const preview=$('#heroPreview');preview.querySelectorAll('video,iframe').forEach(media=>media.remove());preview.style.backgroundImage='';if(!url)return;if(type==='video'){const youtubeId=getYouTubeId(url);if(youtubeId){const iframe=document.createElement('iframe');iframe.src=`https://www.youtube.com/embed/${youtubeId}?autoplay=1&mute=1&loop=1&playlist=${youtubeId}&controls=0&rel=0&playsinline=1&cc_load_policy=0`;iframe.allow='autoplay; encrypted-media';iframe.title='Hero video preview';preview.prepend(iframe)}else{const video=document.createElement('video');video.src=url;video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;preview.prepend(video)}}else preview.style.backgroundImage=`url("${String(url).replace(/["\\]/g,'')}")`}
function getButtonRows(){return [...document.querySelectorAll('.button-row')].map(row=>({label:row.querySelector('.button-label').value.trim(),href:row.querySelector('.button-link').value.trim(),style:row.querySelector('.button-style').value})).filter(button=>button.label&&button.href)}
function syncPreviewText(){const form=$('#heroForm');$('#previewEyebrow').textContent=form.eyebrow.value||'Small heading';$('#previewHeadline').textContent=form.headline.value||'Slide headline';$('#previewDescription').textContent=form.description.value||'Slide description';$('#previewButtons').innerHTML=getButtonRows().map(button=>`<span class="preview-button ${button.style}">${esc(button.label)}</span>`).join('')}
$('#heroForm').addEventListener('input',syncPreviewText);document.querySelectorAll('input[name="mediaType"]').forEach(input=>input.addEventListener('change',updateMediaGuidance));
$('#heroFile').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const type=file.type.startsWith('video/')?'video':'image';$('#heroForm').elements.mediaType.value=type;updateHeroPreview(URL.createObjectURL(file),type)});
$('#addSlideButton').onclick=()=>addButtonRow();$('#addHeroSlide').onclick=resetHeroForm;$('#cancelHeroEdit').onclick=resetHeroForm;
window.editHeroSlide=id=>{const slide=state.settings.heroSlides.find(item=>item.id===id);if(slide)renderHeroForm(slide)};
window.deleteHeroSlide=async id=>{const slide=state.settings.heroSlides.find(item=>item.id===id);if(!confirm(`Delete “${slide?.headline||'this slide'}”?`))return;const response=await fetch('/api/content/settings/hero-slides/'+id,{method:'DELETE'});if(!response.ok)return toast('Unable to delete slide',true);state.settings.heroSlides=state.settings.heroSlides.filter(item=>item.id!==id);renderHeroSlides();renderMetrics();resetHeroForm();toast('Slide deleted')};
$('#heroForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),id=data.get('editingId'),message=$('#heroMessage'),button=form.querySelector('button[type="submit"]');data.delete('editingId');data.delete('durationSeconds');data.set('duration',String(Number(form.durationSeconds.value)*1000));data.set('published',form.published.checked?'true':'false');data.set('buttonsJson',JSON.stringify(getButtonRows()));button.disabled=true;message.className='form-message';message.textContent='Saving...';try{const response=await fetch(id?'/api/content/settings/hero-slides/'+id:'/api/content/settings/hero-slides',{method:id?'PUT':'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save');if(id){const index=state.settings.heroSlides.findIndex(item=>item.id===id);state.settings.heroSlides[index]=result}else state.settings.heroSlides.push(result);renderHeroSlides();renderMetrics();renderHeroForm(result);message.className='form-message success';message.textContent='Slide saved and published to the homepage.';toast('Homepage slide saved')}catch(error){message.className='form-message error';message.textContent=error.message;toast(error.message,true)}finally{button.disabled=false}});

function renderVehicles(filter=''){const list=$('#vehicleList'),query=filter.toLowerCase();const models=state.models.filter(model=>`${model.name} ${model.type}`.toLowerCase().includes(query));$('#vehicleCount').textContent=`${models.length} vehicle${models.length===1?'':'s'}`;list.innerHTML=models.length?models.map(model=>`<article class="vehicle-card"><img src="${esc(model.image)}" alt="${esc(model.name)}"><div class="vehicle-card-body"><div class="vehicle-card-top"><div><h3>${esc(model.name)}</h3><p>${esc(model.type)} · ${esc(model.price)}</p></div><span class="status ${model.published?'':'hidden'}">${model.published?'Published':'Hidden'}</span></div><p>${esc(model.description)}</p><div class="vehicle-card-actions"><button class="secondary" onclick="editVehicle('${esc(model.id)}')">Edit details</button><button class="secondary danger" onclick="deleteVehicle('${esc(model.id)}')">Delete</button></div></div></article>`).join(''):'<p>No matching vehicles found.</p>'}
$('#vehicleSearch').addEventListener('input',event=>renderVehicles(event.target.value));
function renderGalleryPreview(images=[]){$('#vehicleGalleryPreview').innerHTML=images.filter(Boolean).map(image=>`<img src="${esc(image)}" alt="Vehicle gallery preview">`).join('')}
function openVehicle(model){const form=$('#vehicleForm');form.reset();form.editingId.value='';form.published.checked=true;renderGalleryPreview();$('#vehicleFormTitle').textContent='Add new vehicle';$('#vehicleMessage').textContent='';if(model){Object.entries(model).forEach(([key,value])=>{if(form.elements[key]&&key!=='published'&&key!=='images')form.elements[key].value=value||''});form.editingId.value=model.id;form.published.checked=!!model.published;$('#vehicleFormTitle').textContent=`Edit ${model.name}`;renderGalleryPreview(Array.isArray(model.images)&&model.images.length?model.images:[model.image])}$('#vehicleModal').classList.add('open');document.body.style.overflow='hidden'}
function closeVehicle(){$('#vehicleModal').classList.remove('open');document.body.style.overflow=''}
window.editVehicle=id=>openVehicle(state.models.find(model=>model.id===id));
window.deleteVehicle=async id=>{const model=state.models.find(item=>item.id===id);if(!confirm(`Delete ${model?.name||'this vehicle'}? You can hide it instead by editing the listing.`))return;const response=await fetch('/api/content/models/'+id,{method:'DELETE'});if(!response.ok)return toast('Unable to delete vehicle',true);toast('Vehicle deleted');await refreshModels()};
$('#addVehicle').onclick=()=>openVehicle();$('#closeVehicle').onclick=closeVehicle;$('#cancelVehicle').onclick=closeVehicle;$('#vehicleModal').addEventListener('click',event=>{if(event.target.id==='vehicleModal')closeVehicle()});
$('#vehicleFile').addEventListener('change',event=>{const files=[...event.target.files].slice(0,8);renderGalleryPreview(files.map(file=>URL.createObjectURL(file)))});
async function refreshModels(){const response=await fetch('/api/content/models');state.models=await response.json();renderMetrics();renderVehicles($('#vehicleSearch').value)}
$('#vehicleForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),id=data.get('editingId'),message=$('#vehicleMessage'),button=form.querySelector('button[type="submit"]');data.delete('editingId');data.set('published',form.published.checked?'true':'false');button.disabled=true;message.textContent='Saving...';try{const response=await fetch(id?'/api/content/models/'+id:'/api/content/models',{method:id?'PUT':'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save');await refreshModels();closeVehicle();toast(id?'Vehicle updated':'Vehicle added')}catch(error){message.className='form-message error';message.textContent=error.message}finally{button.disabled=false}});
loadAll().catch(()=>toast('Unable to load website content',true));
